services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: labbanco
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab123
    restart: always

  lab-banco:
    image: ghcr.io/yujiyamamoto64/lab-banco:latest
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/labbanco
      SPRING_DATASOURCE_USERNAME: lab
      SPRING_DATASOURCE_PASSWORD: lab123
    depends_on:
      - db
    restart: always
