services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: labbanco
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab123
    restart: always

  lab-banco:
    image: ghcr.io/yujiyamamoto64/lab-banco:latest
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/labbanco
      SPRING_DATASOURCE_USERNAME: lab
      SPRING_DATASOURCE_PASSWORD: lab123
      APP_MOCK_TRANSFER_FIXED_RATE_MS: 60000
      APP_MOCK_TRANSFER_INITIAL_DELAY_MS: 10000
      APP_CHAOS_ENABLED: "true"
      APP_CHAOS_SLEEP_BEFORE_UPDATE_MS: 1500
      APP_CHAOS_FAIL_AFTER_ORIGIN_UPDATE_PROBABILITY: 0.30
    depends_on:
      - db
    restart: always

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    restart: always

  lab-banco-worker:
    image: ghcr.io/yujiyamamoto64/lab-banco:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/labbanco
      SPRING_DATASOURCE_USERNAME: lab
      SPRING_DATASOURCE_PASSWORD: lab123
      APP_MOCK_TRANSFER_FIXED_RATE_MS: 60000
      APP_MOCK_TRANSFER_INITIAL_DELAY_MS: 10000
      APP_CHAOS_ENABLED: "true"
      APP_CHAOS_SLEEP_BEFORE_UPDATE_MS: 1500
      APP_CHAOS_FAIL_AFTER_ORIGIN_UPDATE_PROBABILITY: 0.30
    depends_on:
      - db
    restart: always
